### ISSUE TITLE
Movement feels weird

### ISSUE THREAD

**Issue by ryanisaacg** [fwumdesoft/SmashGame#1]
The game movement feels off. Stopping is too quick, jumps are not quite right, etc.

**Comment by prodrummer5** [comment]
If stopping is too quick, lower the friction.

**Comment by ryanisaacg** [comment]
The issue is for general movement problems- the character controller feels terrible, and it's not just stopping time. Because I wrote the script, I'll try to fix the problems.

**Comment by Ryguy9999** [comment]
the characters are still way too slippery. I tried the knife throw, and the dummy slid for a full second after contact.

**Comment by ryanisaacg** [comment]
@Ryguy9999 That is probably due to the knife knockback being too high.

**Comment by ryanisaacg** [comment]
I'm going to close this issue and create separate issues for each problem with the movement.
